server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Ynwf8ndJANoU4H4ibrao1tOBAd6Cc0w+2CyeySxFO7paolfKSFHjiz7D9Hufkbwb"